/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaapplication4_JavaApplication4 */

#ifndef _Included_javaapplication4_JavaApplication4
#define _Included_javaapplication4_JavaApplication4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaapplication4_JavaApplication4
 * Method:    say
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javaapplication4_JavaApplication4_say
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
